---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "10:00"
      timezone: Asia/Singapore
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "10:00"
      timezone: Asia/Singapore
    commit-message:
      prefix: "pnpm dep"
      prefix-development: "pnpm devDep"
      include: "scope"
    ignore:
      - dependency-name: "vue-tsc"
        versions: ["2.x"]
    pull-request-branch-name:
      separator: "-"
