---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "10:00"
      timezone: Asia/Singapore
    reviewers:
      - "nicholas5538"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "10:00"
      timezone: Asia/Singapore
    reviewers:
      - "nicholas5538"
    pull-request-branch-name:
      separator: "-"
