env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
overrides: [{ files: ["*.js", "*.jsx", "*.ts", "*.tsx"], extends: love }]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  camelcase: error
  default-case: error
  eqeqeq: error
  quotes: ["error", "double", { "avoidEscape": true }]
