env:
  browser: true
  es2021: true
extends:
  - "@nuxt/eslint-config"
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:promise/recommended
  - plugin:prettier/recommended
  - prettier
plugins:
  - import
  - promise
settings:
  import/resolver:
    typescript: true
    node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  camelcase: error
  default-case: error
  eqeqeq: error
  quotes: ["error", "double", { "avoidEscape": true }]
  "vue/multi-word-component-names": off
  "vue/singleline-html-element-content-newline": off
  #  Remove valid-template-root once index.vue is filled with codes
  "vue/valid-template-root": off
