services:
  development:
    build:
      args:
        NODE_VERSION: lts-alpine
      dockerfile: Dockerfile
      target: development
    container_name: nuxt-development
    command: pnpm run dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
  production:
    build:
      args:
        NODE_VERSION: lts-alpine
      dockerfile: Dockerfile
      target: production
    container_name: nuxt-production
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "3000:3000"
