services:
  nuxt-dev:
    build:
      args:
        NODE_VERSION: lts-alpine
      dockerfile: Dockerfile
      target: dev
    container_name: portfolio-nuxt
    command: pnpm run dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
