name: "Approve Dependabot pull request"
on:
  workflow_run:
    workflows: ["End-to-end testing"]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  dependabot-automation:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Find PR from commit SHA
        id: find-pr
        uses: actions/github-script@v7.0.1
        with:
          script: |
            try {
              const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.name,
                commit_sha: context.payload.workflow_run.head_sha,
              });

              if (prs.length === 0) {
                core.setFailed("No PR found for this commit.");
                return;
              }

              const pr = prs.find(p => p.user.login === 'dependabot[bot]');
              if (!pr) {
                core.setFailed("No Dependabot PR found.");
                return;
              }

              core.setOutput('pr-number', pr.number.toString());
            } catch (error) {
              core.setFailed(`Error fetching PR: ${error.message}`);
            }

      - name: Fetch Dependabot metadata
        if: success()
        id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.find-pr.outputs.pr-number }}
        run: |
          gh pr review $PR_NUMBER --approve
