name: "Approve Dependabot pull request"
on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["End-to-end testing"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  dependabot-automation:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'nicholas5538/portfolio-vue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        run: |
          gh pr checkout "$PR_URL"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
