name: "Deploy to AWS Amplify production branch"
on:
  workflow_run:
    workflows: ["Login to Docker Hub and push container"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-aws:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AWS Amplify webhook
        env:
          WEBHOOK: ${{ secrets.AWS_AMPLIFY_PROD_WEBHOOK }}
        run: |
          curl -X POST -d {} $WEBHOOK -H "Content-Type:application/json"
