name: "End-to-end testing"
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run E2E tests
        run: pnpm run test-e2e
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
