name: "End-to-end testing"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      NUXT_GITHUB_SECRET: ${{ secrets.NUXT_GITHUB_SECRET }}

    steps:
      - name: Create env file
        run: |
          touch .env
          echo "NUXT_GITHUB_SECRET=${NUXT_GITHUB_SECRET}" > .env
          cat .env

      - uses: actions/checkout@v4.1.1

      - name: Enable Corepack
        run: corepack enable pnpm

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Run E2E tests
        run: pnpm run test-e2e

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
