name: "Login to Docker Hub and push container"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-docker-hub:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg="NODE_VERSION=lts-alpine" -t portfolio-vue:latest --quiet --compress --target development .
          docker tag portfolio-vue:latest "${DOCKER_USERNAME}/portfolio-vue:latest"
          docker push "${DOCKER_USERNAME}/portfolio-vue:latest"
